name: Terraform CI/CD Dev/Test/Prod

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev/test/prod)"
        required: true
        default: "dev"

jobs:
  terraform:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init -backend-config="key=env-${{ github.event.inputs.environment }}.tfstate"

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      #run: terraform plan -var-file="environments/${{ github.event.inputs.environment }}.tfvars"
      #run: terraform plan -var-file="environments/${{ github.event.inputs.environment}}/terraform.tfvars"
      run: terraform plan \
        -var-file="environments/${{ github.event.inputs.environment }}/terraform.tfvars" \
        -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
        -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
        -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
        -var="tenant_id=${{ secrets.ARM_TENANT_ID }}"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      #run: terraform apply -auto-approve -var-file="environments/${{ github.event.inputs.environment }}.tfvars"
      #run: terraform apply -auto-approve -var-file="environments/${{ github.event.inputs.environment }}/terraform.tfvars"
      run: terraform apply -auto-approve \
        -var-file="environments/${{ github.event.inputs.environment }}/terraform.tfvars" \
        -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
        -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
        -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
        -var="tenant_id=${{ secrets.ARM_TENANT_ID }}"

